name: CI Build

on:
  push:
    branches:
      - next
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.sasi"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.sasi"

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/meson
        with:
          cc: gcc
      - uses: ./.github/actions/doxycheck
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/meson
        with:
          cc: clang
  build-gcc-wayland-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          xcb: false
      - uses: ./.github/actions/meson
        with:
          cc: gcc
          xcb: disabled
  build-gcc-xcb-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          wayland: false
      - uses: ./.github/actions/meson
        with:
          cc: gcc
          wayland: disabled
