site_name: Rofi Documentation
repo_url: https://github.com/davatorium/rofi/
edit_uri: mkdocs/docs/
theme: readthedocs
nav:
  - License: COPYING.md
  - Issue Tracker: https://github.com/davatorium/rofi/issues
  - Discussions Forum: https://github.com/davatorium/rofi/discussions
  - Downloads: downloads.md
  - Installation: INSTALL.md
  - Configuration: CONFIG.md
  - Themes: themes/themes.md
  - Guides:
    - Transparency: guides/Transparency/theme3-transparency.markdown
    - Positioning: guides/Positioning/theme3-positioning.markdown
    - Plugins: guides/Plugins/2017-04-19-rofi-140-sneak-preview-plugins.md
    - Dynamic Theme: guides/DynamicThemes/dynamic_themes.md
  - Current:
    - Rofi: current/rofi.1.markdown 
    - Themes: current/rofi-theme.5.markdown
    - Dmenu: current/rofi-dmenu.5.markdown
    - Script: current/rofi-script.5.markdown
    - Debugging: current/rofi-debugging.5.markdown
    - Keys: current/rofi-keys.5.markdown
    - Thumbnails: current/rofi-thumbnails.5.markdown
    - Actions: current/rofi-actions.5.markdown

plugins:
  - search:
      indexing: full
